language: android
jdk: oraclejdk8
sudo: required

branches:
  - only:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.0
    - android-16
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
    #- sys-img-armeabi-v7a-android-22

#before_script:
  # Create and start emulator
  #- echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  #- emulator -avd test -no-skin -no-audio -no-window &
  #- android-wait-for-emulator
  #- adb shell input keyevent 82 &

before_script:
  - openssl enc -aes-256-cbc -d -k $DECRYPT_PASS -in ./Key/key.jks.enc -out ./Key/key.jks
  - openssl enc -aes-256-cbc -d -k $DECRYPT_PASS -in ./Key/key.json.enc -out ./Key/key.json

script: 
  - ./gradlew build

deploy:
  provider: releases
  api_key:  $GIT_HUB_RELEASE_API_KEY
  file_glob: true
  file: ./app/build/outputs/apk/*
  skip_cleanup: true
  on:
    tags: true
